version: '3'

services:
  producer:
    build: producer
    environment:
      RABBITMQ_NODENAME: proxy
      RABBITMQ_NODE_PORT: 55000
    depends_on:
      - rmq
      - proxy
      - proxy-sidecar
  consumer:
    build: consumer
    environment:
      RABBITMQ_NODENAME: proxy
      RABBITMQ_NODE_PORT: 55001
    depends_on:
      - rmq
      - proxy
      - proxy-sidecar
  proxy:
    image: ghcr.io/shopify/toxiproxy:latest
    hostname: proxy
  proxy-sidecar:
    build: proxy-sidecar
    depends_on:
      - proxy
  rmq:
    build: rmq
    hostname: rabbitmq
    environment:
      LOG: debug
    ports:
      # HOST:CONTAINER
      - 15672:15672
